<?php
/**
 * An exception that is probably generated by user input.
 * This exception's messages should only contain safe-to-display information
 * @author Cornel Borina <cornel@scoalaweb.com>
 * @package 3oLibrary
 * @subpackage Exceptions
 */
class UserInputException extends Exception {
    private $field = '';
    /**
     * @see Exception
     * @param string $message
     * @param string $field - the form field that produced the error (optional)
     */
    public function __construct($message, $field = '', $code = 0, $previous = null) {
        parent::__construct($message, $code, $previous);
        $this->field = $field;
    }
    
    /**
     * Return the form field from witch the error originated
     * @return string
     */
    public function getField() {
        return $this->field;
    }
}
